services:
  grafana:
    image: grafana/grafana:13.0.3
    container_name: zbx-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=change-me-on-first-login
    ports:
      - "3001:3000"   # única porta exposta pra acesso humano (3000 já em uso por outro serviço nos nós)
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
    networks:
      - zbx-observability-net

networks:
  zbx-observability-net:
    external: true

volumes:
  grafana-data:
